[debug] "not up to date. inChanged = true, force = false
[debug] Updating ProjectRef(uri("file:/C:/Users/Tofig.Bakshiyev/Desktop/ScalaConcurrent/"), "scalaconcurrent")...
[error] java.io.FileNotFoundException: C:\Users\Tofig.Bakshiyev\AppData\Local\Coursier\cache\v1\.structure.lock (Access is denied)
[error] 	at java.base/java.io.FileOutputStream.open0(Native Method)
[error] 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
[error] 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
[error] 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
[error] 	at lmcoursier.internal.shaded.coursier.paths.CachePath.withStructureLock(CachePath.java:128)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:21)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:38)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:506)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (updateClassifiers) java.io.FileNotFoundException: C:\Users\Tofig.Bakshiyev\AppData\Local\Coursier\cache\v1\.structure.lock (Access is denied)
